# Generated by Django 4.2.16 on 2025-09-20 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('policies', 'Policies & Guidelines'), ('operations', 'Operations & Production'), ('maintenance', 'Maintenance & Technical Manuals'), ('training', 'Training & Knowledge Base'), ('others', 'Others')], max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
