# Generated by Django 4.2.16 on 2025-09-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='classification_method',
            field=models.CharField(blank=True, help_text='Method used for classification (folder, comprehend, text)', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='comprehend_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='document',
            name='textract_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, choices=[('policies', 'Policies & Guidelines'), ('operations', 'Operations & Production'), ('maintenance', 'Maintenance & Technical Manuals'), ('training', 'Training & Knowledge Base'), ('safety', 'Safety & Risk Management'), ('quality', 'Quality & Compliance'), ('others', 'Others')], max_length=20),
        ),
    ]
