# Generated by Django 4.2.16 on 2025-09-21 13:25

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0003_update_categories_and_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.CharField(help_text='Document ID from Kendra or local database', max_length=255)),
                ('document_title', models.CharField(max_length=500)),
                ('document_category', models.CharField(blank=True, max_length=100)),
                ('action_type', models.CharField(choices=[('view', 'View'), ('download', 'Download')], max_length=10)),
                ('user_session', models.CharField(blank=True, help_text='User session identifier', max_length=100)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='document_ap_timesta_3a24d4_idx'), models.Index(fields=['user_session', '-timestamp'], name='document_ap_user_se_8187e7_idx'), models.Index(fields=['document_id'], name='document_ap_documen_feb849_idx')],
            },
        ),
    ]
